use  prograweb;

CREATE TABLE `estatus` (
  `CLAVE-ESTATUS` int NOT NULL AUTO_INCREMENT,
  `ESTATUS` varchar(45) NOT NULL,
  PRIMARY KEY (`CLAVE-ESTATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='tabla para saber si un usuario/publicacion esta dad@ de baja.';

CREATE TABLE `usuarios` (
  `CLAVE-USUARIOS` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(200) NOT NULL,
  `APELLIDOM` varchar(45) NOT NULL,
  `APELLIDOP` varchar(45) NOT NULL,
  `CONTRASEÑA` varchar(45) NOT NULL,
  `NOMBRE-USER` varchar(45) NOT NULL,
  `CORREO` varchar(45) NOT NULL,
  `FECHA-NACIMIENTO` date NOT NULL,
  `FOTO-PERIL` varchar(100) NOT NULL,
  `FECHA-CREACION` date NOT NULL,
  `ESTATUS` varchar(45) NOT NULL,
  `EDAD` varchar(45) NOT NULL,
  `CLAVE-ESTATUS` int NOT NULL,
  PRIMARY KEY (`CLAVE-USUARIOS`),
  KEY `FK-ESTATUS_idx` (`ESTATUS`),
  KEY `FK-CLAVE-ESTATUS_idx` (`CLAVE-ESTATUS`),
  CONSTRAINT `FK-CLAVE-ESTATUS` FOREIGN KEY (`CLAVE-ESTATUS`) REFERENCES `estatus` (`CLAVE-ESTATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `categorias` (
  `CLAVE-CATEGORIAS` int NOT NULL AUTO_INCREMENT,
  `NOMBRE-CATEGORIAS` varchar(45) NOT NULL,
  PRIMARY KEY (`CLAVE-CATEGORIAS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='tabla para el catalogo de las categorias de las publicaciones.';

CREATE TABLE `publicaciones` (
  `CLAVE-PUBLICACIONES` int NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(45) NOT NULL,
  `CONTENIDO` varchar(45) NOT NULL,
  `FECHA` date NOT NULL,
  `MEDIA` varchar(45) NOT NULL,
  `CLAVE-USUARIOS` int NOT NULL,
  `CLAVE-ESTATUS` int NOT NULL,
  PRIMARY KEY (`CLAVE-PUBLICACIONES`),
  KEY `FK-CLAVE-ESTATUS_idx` (`CLAVE-ESTATUS`),
  KEY `FK-CLAVE-USUARIO-PUBLICACION_idx` (`CLAVE-USUARIOS`),
  CONSTRAINT `FK-CLAVE-ESTATUS-PUBLICACION` FOREIGN KEY (`CLAVE-ESTATUS`) REFERENCES `estatus` (`CLAVE-ESTATUS`),
  CONSTRAINT `FK-CLAVE-USUARIO-PUBLICACION` FOREIGN KEY (`CLAVE-USUARIOS`) REFERENCES `usuarios` (`CLAVE-USUARIOS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='tabla para los post realizados por los usuarios';

CREATE TABLE `categorias-publicacion` (
  `CLAVE-CATEGORIAS-PUBLICACION` int NOT NULL AUTO_INCREMENT,
  `CLAVE-CATEGORIAS` int NOT NULL,
  `CLAVE-PUBLICACION` int NOT NULL,
  PRIMARY KEY (`CLAVE-CATEGORIAS-PUBLICACION`),
  KEY `FK-CLAVE-PUBLICACIONES_idx` (`CLAVE-PUBLICACION`),
  KEY `FK-CLAVE-CATEGORIAS_idx` (`CLAVE-CATEGORIAS`),
  CONSTRAINT `FK-CLAVE-CATEGORIAS` FOREIGN KEY (`CLAVE-CATEGORIAS`) REFERENCES `categorias` (`CLAVE-CATEGORIAS`),
  CONSTRAINT `FK-CLAVE-PUBLICACIONES` FOREIGN KEY (`CLAVE-PUBLICACION`) REFERENCES `publicaciones` (`CLAVE-PUBLICACIONES`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;